version: '3.8'
services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        restart: unless-stopped

    app:
        build: .
        env_file:
            - .env.docker
        expose:
            - "9000"
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - .:/var/www
        restart: unless-stopped

    db:
        image: mysql:8.0
        command:
            -   --max_connections=500
        environment:
            MYSQL_ROOT_PASSWORD: shoaibmesta2002
            MYSQL_DATABASE: laundryapi
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pshoaibmesta2002"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

volumes:
    db_data:
